// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:04f09d8d-cf06-44a8-95a8-7324e1d60913",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ttYH649Q9",
    "aws_user_pools_web_client_id": "om098mnpbkbiclm4ru9b2nd4i"
};


export default awsmobile;
